matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env: SWIFT_SNAPSHOT=5.0.1
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=5.0.1
    - os: linux
      dist: trusty
      sudo: required
      env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=5.0.1

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
