#if !canImport(ObjectiveC)
import XCTest

extension PureMarkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PureMarkTests = [
        ("testCodeBlock", testCodeBlock),
        ("testEscape", testEscape),
        ("testHeaders", testHeaders),
        ("testHorizontalRule", testHorizontalRule),
        ("testImageRender", testImageRender),
        ("testList", testList),
        ("testParagraph", testParagraph),
        ("testSimpleBlockquote", testSimpleBlockquote),
        ("testSimpleLinkRender", testSimpleLinkRender),
        ("testStyledBlockquote", testStyledBlockquote),
        ("testStyledLinkRender", testStyledLinkRender),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PureMarkTests.__allTests__PureMarkTests),
    ]
}
#endif
